# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_GID "-1")
set(CPACK_ARCHIVE_UID "-1")
set(CPACK_BUILD_SOURCE_DIRS "/home/sebastien/ABLS-AGENT-DLS;/home/sebastien/ABLS-AGENT-DLS/build_orig")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "runtime")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_RUNTIME_PACKAGE_CONTROL_EXTRA "/home/sebastien/ABLS-AGENT-DLS/packaging/deb/postinst;/home/sebastien/ABLS-AGENT-DLS/packaging/deb/prerm;/home/sebastien/ABLS-AGENT-DLS/packaging/deb/postrm")
set(CPACK_DEBIAN_RUNTIME_PACKAGE_DEPENDS "libglib2.0-0, libjson-glib-1.0-0, abls-libs, abls-agent-libs")
set(CPACK_DEBIAN_RUNTIME_PACKAGE_NAME "abls-agent-dls")
set(CPACK_DEBIAN_RUNTIME_PACKAGE_SHLIBDEPS "ON")
set(CPACK_DEB_COMPONENT_INSTALL "ON")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "abls-agent-dls built using CMake")
set(CPACK_GENERATOR "RPM;DEB")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/sebastien/ABLS-AGENT-DLS/build_orig;abls-agent-dls;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "abls-agent-dls 0.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "abls-agent-dls 0.0")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/sebastien/ABLS-AGENT-DLS/build_orig/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "sebastien.lefevre@abls-habitat.fr")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Abls Habitat DLS runtime")
set(CPACK_PACKAGE_FILE_NAME "abls-agent-dls-0.0-Linux")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://docs.abls-habitat.fr")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "abls-agent-dls 0.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "abls-agent-dls 0.0")
set(CPACK_PACKAGE_LICENSE "GPLv3")
set(CPACK_PACKAGE_NAME "abls-agent-dls")
set(CPACK_PACKAGE_RELEASE "1")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Abls-Habitat")
set(CPACK_PACKAGE_VERSION "0.0")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/usr/share/cmake/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_COMPONENT_INSTALL "ON")
set(CPACK_RPM_RUNTIME_BUILD_SOURCE_DIRS_PREFIX "/usr/src/debug")
set(CPACK_RPM_RUNTIME_DEBUGINFO_FILE_NAME "RPM-DEFAULT")
set(CPACK_RPM_RUNTIME_DEBUGINFO_PACKAGE "ON")
set(CPACK_RPM_RUNTIME_FILE_NAME "abls-agent-dls-0.0-1.rpm")
set(CPACK_RPM_RUNTIME_PACKAGE_NAME "abls-agent-dls")
set(CPACK_RPM_RUNTIME_PACKAGE_REQUIRES "glib2, json-glib, abls-libs, abls-agent-libs")
set(CPACK_RPM_RUNTIME_PACKAGE_SUMMARY "Abls-Habitat DLS runtime")
set(CPACK_RPM_RUNTIME_POST_INSTALL_SCRIPT_FILE "/home/sebastien/ABLS-AGENT-DLS/packaging/rpm/runtime.postinst")
set(CPACK_RPM_RUNTIME_POST_UNINSTALL_SCRIPT_FILE "/home/sebastien/ABLS-AGENT-DLS/packaging/rpm/runtime.postun")
set(CPACK_RPM_RUNTIME_PRE_UNINSTALL_SCRIPT_FILE "/home/sebastien/ABLS-AGENT-DLS/packaging/rpm/runtime.preun")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/sebastien/ABLS-AGENT-DLS/build_orig/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/sebastien/ABLS-AGENT-DLS/build_orig/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
